### ISSUE TITLE
能否安排秘钥登录，代理服务器连接功能

### ISSUE THREAD

**Issue by zundaren** [zhangdapeng520/zdpgo_ssh#1]
秘钥登录，代理服务器连接功能

**Comment by DapengAiTeach** [comment]
可以的，我有时间了研究下。谢谢您的建议。

**Comment by DapengAiTeach** [comment]
> 秘钥登录，代理服务器连接功能

已经解决了哈，可以试一下新版的。我在Windows上测试了连接Centos7的虚拟机是没有问题的。
